### ISSUE TITLE
Compiling errors when using the command

### ISSUE THREAD

**Issue by WilliamWangPeng** [CIS565-Fall-2015/Project3-CUDA-Path-Tracer#18]
HI dear author,  
    It's truly a honor to write a letter to you,  I'm building your project nowadays and found the error when building as following, I wonder if there is a chance that you know the reason? :)

![image](https://user-images.githubusercontent.com/51076736/116841680-7fe17880-ac0c-11eb-9809-8712fac2bb63.png)

thank you  
best regards to you  
William

**Comment by kainino0x** [comment]
Please consider trying the latest version of this project instead. https://github.com/CIS565-Fall-2020/Project3-CUDA-Path-Tracer

It is likely that the CUDA tools no longer support sm_20. You can try picking a newer SM. This theory is confirmed by this page: https://arnon.dk/matching-sm-architectures-arch-and-gencode-for-various-nvidia-cards/
